### ISSUE TITLE
Check runscript for core count allocation

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/SE-NEMO#105]
@katavouta has mentioned that the ZPS and MES core count setups in the runscript are the same - with the ZPS (? I think) one not working for her. 

- [x]  Check old directories/branches to see if there were at any point alternative options

Re-test current options with the standard domain_cfg files for 

- [x] MES
- [x] ZPS

Also, as we're now running on an updated ARCHER2, report back timings for 1 months run of all options.

**Comment by jdha** [comment]
@katavouta can you remind me what core count you used for MES/ZPS runs so I can double check against what works for me. Thanks

**Comment by katavouta** [comment]
@jdha for the MES the options within the runscript.slurm (from the EXPREF) work fine for me (ln_zps=false). For the zps runs the options ln_zps=true within the runscript.slurm do not work for me. I instead used and run fine with:
elif [ $SLURM_NNODES -eq 76 ]
   then
      SRUN_CMD=`./slurm_setup -S 8 -s 16 -m 1 -C 6429 -g 3 -N 128 -t 01:00:00 -a n01-CLASS -j se-nemo`

(which I found it from ...  SE-NEMO/scripts/run/archer2/runscript.slurm.GS1p0_notide)

**Comment by jdha** [comment]
Performance for MES:

| Nodes | Time hrs/yr |
|-------|-----------|
| 19 | 4.7 |
| 29 | 2.6 |
| 52 | 1.7 |
| 68 | 1.4 |
| 72 | 1.4 |

All `ocean.ouputs` check and we're using the best decomposition 

Performance for ZPS:

| Nodes | Time hrs/yr |
|-------|-----------|
| 19 | 4.6 |
| 29 | 2.3 |
| 52 | 1.6 |
| 68 | 1.5 |

All `ocean.ouputs` check and we're using the best decomposition 

ZPS optimised core count:

| Nodes | Cores |
|-------|-----------|
| 19 | 1509 |
| 29 | 2964 |
| 52 | 6221 |
| 68 | 7948 |
