### ISSUE TITLE
Likely bug in IWD code

### ISSUE THREAD

**Issue by chris-O-wilson** [NOC-MSM/SE-NEMO#123]
https://github.com/NOC-MSM/SE-NEMO/blob/9203f9689c22e6703eabde827782d4887fcce5ca/MY_SRC_TIDE/dynspg_ts.F90#L1704C28-L1704C29

Likely division by zero or zero/zero in dynspg_ts.F90 needs error-trapping.

**Comment by jasontempestholt** [comment]
Fixed with commit to IWD
