### ISSUE TITLE
htau_scaling 

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/SE-NEMO#151]
in 4.2.1 there is a namelist variable `htau_scaling` that doesn't appear in the code. It isn't present in 4.0.4 and it also doesn't appear in 4.2.2. Not sure where it's come from.

**Comment by atb299** [comment]
@jdha, it is part of the Southern Ocean package that went into GOSI9:

" Tuning of the e-folding length scale nn\_htau associated with the parameterisation of near-inertial wave breaking resulted in the choice of a larger length scale in the Southern Ocean \citep[Fig. 2]{Storkey2018} where summertime climatological \citep{DeBoyerMontegut2004} mixed layers are on average deeper than in the northern latitudes. Revisiting this work we found that reducing the mixing depth between 10$^{\circ}$ and 40$^{\circ}$ S improved the warm subsurface bias in the Indian Ocean.  The changes were tested in the forced eORCA025 GOSI9 configuration before being implemented as standard in the three GOSI9 configurations. "

All references to it are (I believe) in zdftke.F90:

zdftke.F90:   REAL(wp) ::      rn_htau_scaling   ! a acaling factor to apply to the penetration of TKE
zdftke.F90:         &                 rn_htau_scaling    ,                        &
zdftke.F90:         WRITE(numout,*) '          scaling factor for tke penetration depth   rn_htau_scaling   = ', rn_htau_scaling
zdftke.F90:            htau(:,:) = rn_htau_scaling*10._wp
zdftke.F90:                     htau(ji,jj) = MAX(  0.5_wp, MIN( 30._wp, 45._wp* rn_htau_scaling*ABS( SIN( rpi/180._wp * gphit(ji,jj) ) ) )   )
zdftke.F90:                     htau(ji,jj) = MAX(  0.5_wp, MIN( 10._wp, 45._wp* rn_htau_scaling*ABS( SIN( rpi/180._wp * gphit(ji,jj) ) ) )   )
zdftke.F90:                  htau(ji,jj) = MAX(  0.5_wp, MIN( 10._wp, 45._wp* rn_htau_scaling*ABS( SIN( rpi/180._wp * gphit(ji,jj) ) ) )   )

**Comment by jdha** [comment]
@atb299 - yes I realise its purpose ... this was just a ticket to workout how I manage to include it into the `namelist_ref` for 4.2.1 and it not being in the code. I thought I'd just merged the NEMO 4.2.1 tag with SE-NEMO at 4.0.4 ... so I'm a little puzzled how it got into the namelist!

**Comment by atb299** [comment]
Is is because you use(d) GLS instead of TKE? If the code was there, you wanted to activate it you'd need to set nn_htau  = 4 or 5 in the namelist. Looking at a GO6 namelist, I think a variant of it was present even at v3.6.

**Comment by jdha** [comment]
No we've used both - and when we've run with TKE we've run with `nn_htau =4` ... In the 4.0.4 GO8 code we have there is no scaling applied using option 4

**Comment by jdha** [comment]
Ha! Just figured out what's happened (will confirm when ARCHER2 is back online). When I merged tag 4.2.1 and SE-NEMO 4.0.4 I also had an eye on the NPD 4.2.1. I think the fact you've edited `SHARED/namelist_ref` has probably thrown me - and that's where `rn_htau_scaling` has crept in. I tend to leave my `SHARED` directory untouched and any namelist mods based on `MY_SRC` go into an updated `namelist_ref` in the `EXP` dir. Will have to look again at the NPD and see if we can align SE-NEMO with NPD going forward!

**Comment by atb299** [comment]
Interesting, I use  nn_htau  =  5. I've just tracked that down to the change from GO8p7 to GOSI9p8 (see https://code.metoffice.gov.uk/trac/GO/wiki/GODocumentation/GO8.0/GO8Releases )

"4. The TKE mixing depth has been reduced. This change results in the deepening of the MLD in a band around 40S associated with a SST warming in winter and cooling in summer."

**Comment by jdha** [comment]
Closing for now. I've left `rn_htau_scaling` in the 4.2.2 namelist_ref but commented out. I will raise a further ticket addressing the streamlining of the code towards NPD after I've had a chat with @atb299 about the best way forward.
