### ISSUE TITLE
out of bound array

### ISSUE THREAD

**Issue by yutiPML** [NOC-MSM/SE-NEMO#92]
in MY_SRC_GO8_FROZEN/icethd_pnd.F90 line 650 zTavg is calculated using an out of bound value for the index jl

I suspect that instead of dividing by a single (non-existing) value of a_i, it should be divided by the sum of a_i along the third axis.

However, zTavg is defined as local variable (line 519), calculated (lines 645-650) but never used.

quick fix is to comment line 650

This problem is only highlighted when the code is compiled with -fcheck=all

**Comment by jdha** [comment]
@chris-O-wilson & @jasontempestholt updated code - now in master.
